### ISSUE TITLE
Custom Build Behavior

### ISSUE THREAD

**Issue by iammerrick** [guybedford/amd-loader#1]
I am loving the idea of this project. Often times in building Require.js plugins the need to run something different for the build to say, generate strings... Where as in the browser to export interfaces. I am having trouble seeing where the build specific implementation should exist, take for example Handlebars...
## Runtime

``` javascript
  callback(Handlebars.compile(template));
```
## Buildtime

``` javascript
  // Potentially do lots of other mutation here...
  callback(Handlebars.precompile(template));
```

Using amd-loader how would one provide build specific and runtime specific functionality?

**Comment by guybedford** [comment]
Good question. I have a basic Handlebars plugin with it here - https://github.com/guybedford/hbs.

A cool feature is that helpers can be referenced as moduleIDs in the template itself with full build support.

The way I dealt with the issue there is to return source code that has imports with a "define" statement.

There is also the ability to write the plugin and builder as separate modules with the "pluginBuilder" functionality too.

**Comment by iammerrick** [comment]
So whatever gets passed into the callback gets evaluated or written for the build?

**Comment by guybedford** [comment]
Exactly, the callback takes the compiled source, which gets written for the build, and can handle dependencies for building. These can be different modules by using a "pluginBuilder".

In the client, it uses eval but the assumption is that this is typically development-only for dynamic requires.

There is also the ability to "precompile" templates, using the "optimizeAllPluginResources" RequireJS build option. Setting `config.precompiled` to true will turn on that feature. This way dynamic single template requires can be made in production, but I'm not sure how useful that is.
