### ISSUE TITLE
Server ~ Client detection.

### ISSUE THREAD

**Issue by M3kH** [guybedford/amd-loader#2]
Hi @guybedford !
Thanks for this sweat library, I'm currently using with Ractive.js and I try to run them in node.js

I just got an issue when obj window is declared inside a node application, so I decide to fork it and try to do a dirty fix. Do you think could be useful for the library? Do you need a pul request?

**Comment by guybedford** [comment]
Glad you like the module. Yes, a pull request would be very much welcome if it fixes a bug in this project. Thanks.

**Comment by M3kH** [comment]
Sorry, Maybe wasn't that important. :+1:
