### ISSUE TITLE
bower registry

### ISSUE THREAD

**Issue by gig177** [guybedford/amd-loader#3]
Please register your package on http://bower.herokuapp.com/packages/. By default bower will install package from git://github.com/ajaxorg/node-amd-loader.git

**Comment by guybedford** [comment]
Thanks, I'm not actually supporting this repo anymore though.

**Comment by gig177** [comment]
Are you using something more powerful or requirejs is not your choice anymore?

**Comment by guybedford** [comment]
I'm using jspm.

**Comment by gig177** [comment]
Thank you.
